version: '3'
services:
  # hazelcast imdg
  hazelcast:
    image: barisaydinoz/hz-zk:1
    ports:
      - "5701:5701"
    deploy:
      replicas: 3
    networks:
      - backend
    volumes:
        - .:/configFolder
    environment:
        - JAVA_OPTS=-Dhazelcast.config=/configFolder/hazelcast.xml

  # visualizer
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

# networks
networks:
  backend:
